import type { AllergenCode, CategoryCode, UnitCode } from './reference-data.js';

/**
 * Katalog składników startowych. Wartości odżywcze pochodzą z USDA FoodData Central
 * (SR Legacy, domena publiczna) - wyciąga je `tools/usda-extract.ts` do `ingredients.data.json`.
 * Tu trzymamy tylko to, czego w USDA nie ma: polskie nazwy, kategorie, alergeny UE
 * i typowe gramatury jednostek kuchennych.
 *
 * Gramatury (`units`) to wartości orientacyjne: średnia sztuka / łyżka bez czubka.
 */
export interface CatalogItem {
  pl: string;
  en: string;
  /** Dokładny opis w bazie USDA SR Legacy */
  usda: string;
  category: CategoryCode;
  allergens?: AllergenCode[];
  /** Gęstość w g/ml - tylko dla płynów (pozwala przeliczać ml ↔ g) */
  density?: number;
  /** Gramy na jednostkę */
  units?: Partial<Record<UnitCode, number>>;
}

const V = 'VEGETABLES';
const F = 'FRUITS';

export const INGREDIENT_CATALOG: CatalogItem[] = [
  // --- Warzywa -----------------------------------------------------------------
  {
    pl: 'Pomidor',
    en: 'Tomato',
    usda: 'Tomatoes, red, ripe, raw, year round average',
    category: V,
    units: { PIECE: 120, SLICE: 20 },
  },
  {
    pl: 'Pomidor koktajlowy',
    en: 'Cherry tomato',
    usda: 'Tomatoes, red, ripe, raw, year round average',
    category: V,
    units: { PIECE: 17, HANDFUL: 100 },
  },
  {
    pl: 'Ogórek',
    en: 'Cucumber',
    usda: 'Cucumber, with peel, raw',
    category: V,
    units: { PIECE: 200, SLICE: 7 },
  },
  {
    pl: 'Ziemniaki',
    en: 'Potatoes',
    usda: 'Potatoes, white, flesh and skin, raw',
    category: V,
    units: { PIECE: 150 },
  },
  {
    pl: 'Batat',
    en: 'Sweet potato',
    usda: "Sweet potato, raw, unprepared (Includes foods for USDA's Food Distribution Program)",
    category: V,
    units: { PIECE: 200 },
  },
  { pl: 'Marchew', en: 'Carrot', usda: 'Carrots, raw', category: V, units: { PIECE: 60 } },
  { pl: 'Cebula', en: 'Onion', usda: 'Onions, raw', category: V, units: { PIECE: 110, TABLESPOON: 10 } },
  { pl: 'Cebula czerwona', en: 'Red onion', usda: 'Onions, sweet, raw', category: V, units: { PIECE: 110 } },
  { pl: 'Szalotka', en: 'Shallot', usda: 'Shallots, raw', category: V, units: { PIECE: 30, TABLESPOON: 10 } },
  {
    pl: 'Dymka (szczypior z cebulką)',
    en: 'Spring onion',
    usda: 'Onions, spring or scallions (includes tops and bulb), raw',
    category: V,
    units: { PIECE: 15, BUNCH: 100 },
  },
  {
    pl: 'Czosnek',
    en: 'Garlic',
    usda: 'Garlic, raw',
    category: V,
    units: { CLOVE: 4, PIECE: 45, TEASPOON: 3 },
  },
  {
    pl: 'Por',
    en: 'Leek',
    usda: 'Leeks, (bulb and lower leaf-portion), raw',
    category: V,
    units: { PIECE: 180 },
  },
  {
    pl: 'Papryka czerwona',
    en: 'Red bell pepper',
    usda: 'Peppers, sweet, red, raw',
    category: V,
    units: { PIECE: 150 },
  },
  {
    pl: 'Papryka zielona',
    en: 'Green bell pepper',
    usda: 'Peppers, sweet, green, raw',
    category: V,
    units: { PIECE: 150 },
  },
  {
    pl: 'Papryka żółta',
    en: 'Yellow bell pepper',
    usda: 'Peppers, sweet, yellow, raw',
    category: V,
    units: { PIECE: 150 },
  },
  {
    pl: 'Papryczka chili',
    en: 'Chili pepper',
    usda: 'Peppers, hot chili, red, raw',
    category: V,
    units: { PIECE: 15 },
  },
  {
    pl: 'Papryczka jalapeño',
    en: 'Jalapeño',
    usda: 'Peppers, jalapeno, raw',
    category: V,
    units: { PIECE: 15 },
  },
  {
    pl: 'Cukinia',
    en: 'Zucchini',
    usda: 'Squash, summer, zucchini, includes skin, raw',
    category: V,
    units: { PIECE: 250 },
  },
  { pl: 'Dynia', en: 'Pumpkin', usda: 'Pumpkin, raw', category: V },
  {
    pl: 'Dynia piżmowa',
    en: 'Butternut squash',
    usda: 'Squash, winter, butternut, raw',
    category: V,
    units: { PIECE: 1200 },
  },
  { pl: 'Bakłażan', en: 'Eggplant', usda: 'Eggplant, raw', category: V, units: { PIECE: 300 } },
  { pl: 'Kapusta biała', en: 'White cabbage', usda: 'Cabbage, raw', category: V, units: { PIECE: 1500 } },
  {
    pl: 'Kapusta czerwona',
    en: 'Red cabbage',
    usda: 'Cabbage, red, raw',
    category: V,
    units: { PIECE: 1200 },
  },
  {
    pl: 'Kapusta włoska',
    en: 'Savoy cabbage',
    usda: 'Cabbage, savoy, raw',
    category: V,
    units: { PIECE: 1000 },
  },
  {
    pl: 'Kapusta pekińska',
    en: 'Napa cabbage',
    usda: 'Cabbage, chinese (pak-choi), raw',
    category: V,
    units: { PIECE: 900 },
  },
  {
    pl: 'Kiszona kapusta',
    en: 'Sauerkraut',
    usda: 'Sauerkraut, canned, solids and liquids',
    category: V,
    units: { GLASS: 140 },
  },
  { pl: 'Brokuł', en: 'Broccoli', usda: 'Broccoli, raw', category: V, units: { PIECE: 350 } },
  { pl: 'Kalafior', en: 'Cauliflower', usda: 'Cauliflower, raw', category: V, units: { PIECE: 600 } },
  {
    pl: 'Brukselka',
    en: 'Brussels sprouts',
    usda: 'Brussels sprouts, raw',
    category: V,
    units: { PIECE: 15 },
  },
  { pl: 'Jarmuż', en: 'Kale', usda: 'Kale, raw', category: V, units: { HANDFUL: 30 } },
  { pl: 'Szpinak', en: 'Spinach', usda: 'Spinach, raw', category: V, units: { HANDFUL: 30 } },
  { pl: 'Rukola', en: 'Arugula', usda: 'Arugula, raw', category: V, units: { HANDFUL: 20 } },
  {
    pl: 'Sałata masłowa',
    en: 'Butter lettuce',
    usda: 'Lettuce, butterhead (includes boston and bibb types), raw',
    category: V,
    units: { PIECE: 250 },
  },
  {
    pl: 'Sałata lodowa',
    en: 'Iceberg lettuce',
    usda: 'Lettuce, iceberg (includes crisphead types), raw',
    category: V,
    units: { PIECE: 500 },
  },
  {
    pl: 'Sałata rzymska',
    en: 'Romaine lettuce',
    usda: 'Lettuce, cos or romaine, raw',
    category: V,
    units: { PIECE: 400 },
  },
  { pl: 'Botwina', en: 'Beet greens', usda: 'Beet greens, raw', category: V, units: { BUNCH: 300 } },
  {
    pl: 'Boćwina (burak liściowy)',
    en: 'Swiss chard',
    usda: 'Chard, swiss, raw',
    category: V,
    units: { BUNCH: 300 },
  },
  { pl: 'Burak', en: 'Beetroot', usda: 'Beets, raw', category: V, units: { PIECE: 150 } },
  {
    pl: 'Seler korzeniowy',
    en: 'Celeriac',
    usda: 'Celeriac, raw',
    category: V,
    allergens: ['CELERY'],
    units: { PIECE: 500 },
  },
  {
    pl: 'Seler naciowy',
    en: 'Celery',
    usda: 'Celery, raw',
    category: V,
    allergens: ['CELERY'],
    units: { PIECE: 40 },
  },
  { pl: 'Pietruszka (korzeń)', en: 'Parsley root', usda: 'Parsnips, raw', category: V, units: { PIECE: 80 } },
  { pl: 'Pasternak', en: 'Parsnip', usda: 'Parsnips, raw', category: V, units: { PIECE: 120 } },
  { pl: 'Rzodkiewka', en: 'Radish', usda: 'Radishes, raw', category: V, units: { PIECE: 10, BUNCH: 150 } },
  { pl: 'Rzepa', en: 'Turnip', usda: 'Turnips, raw', category: V, units: { PIECE: 120 } },
  { pl: 'Kalarepa', en: 'Kohlrabi', usda: 'Kohlrabi, raw', category: V, units: { PIECE: 250 } },
  {
    pl: 'Koper włoski (fenkuł)',
    en: 'Fennel',
    usda: 'Fennel, bulb, raw',
    category: V,
    units: { PIECE: 230 },
  },
  { pl: 'Szparagi', en: 'Asparagus', usda: 'Asparagus, raw', category: V, units: { PIECE: 16, BUNCH: 500 } },
  {
    pl: 'Karczoch',
    en: 'Artichoke',
    usda: 'Artichokes, (globe or french), raw',
    category: V,
    units: { PIECE: 130 },
  },
  { pl: 'Cykoria', en: 'Endive', usda: 'Endive, raw', category: V, units: { PIECE: 120 } },
  {
    pl: 'Groszek zielony',
    en: 'Green peas',
    usda: 'Peas, green, raw',
    category: V,
    units: { GLASS: 150, TABLESPOON: 10 },
  },
  {
    pl: 'Fasolka szparagowa',
    en: 'Green beans',
    usda: 'Beans, snap, green, raw',
    category: V,
    units: { HANDFUL: 60 },
  },
  {
    pl: 'Fasolka szparagowa żółta',
    en: 'Yellow wax beans',
    usda: 'Beans, snap, yellow, raw',
    category: V,
    units: { HANDFUL: 60 },
  },
  {
    pl: 'Kukurydza',
    en: 'Sweet corn',
    usda: 'Corn, sweet, yellow, raw',
    category: V,
    units: { PIECE: 250, TABLESPOON: 12 },
  },
  {
    pl: 'Awokado',
    en: 'Avocado',
    usda: 'Avocados, raw, all commercial varieties',
    category: V,
    units: { PIECE: 150 },
  },
  {
    pl: 'Oliwki zielone',
    en: 'Green olives',
    usda: 'Olives, pickled, canned or bottled, green',
    category: V,
    units: { PIECE: 4, TABLESPOON: 15 },
  },
  {
    pl: 'Oliwki czarne',
    en: 'Black olives',
    usda: 'Olives, ripe, canned (small-extra large)',
    category: V,
    units: { PIECE: 4, TABLESPOON: 15 },
  },
  {
    pl: 'Ogórek kiszony',
    en: 'Pickled cucumber',
    usda: 'Pickles, cucumber, sour',
    category: V,
    units: { PIECE: 70 },
  },
  {
    pl: 'Ogórek konserwowy',
    en: 'Dill pickle',
    usda: 'Pickles, cucumber, dill or kosher dill',
    category: V,
    units: { PIECE: 40 },
  },
  { pl: 'Kapary', en: 'Capers', usda: 'Capers, canned', category: V, units: { TEASPOON: 3, TABLESPOON: 9 } },
  {
    pl: 'Chrzan tarty',
    en: 'Prepared horseradish',
    usda: 'Horseradish, prepared',
    category: 'SAUCES',
    units: { TEASPOON: 5, TABLESPOON: 15 },
  },
  {
    pl: 'Imbir świeży',
    en: 'Fresh ginger',
    usda: 'Ginger root, raw',
    category: V,
    units: { TEASPOON: 2, PIECE: 30 },
  },
  {
    pl: 'Pomidory z puszki',
    en: 'Canned tomatoes',
    usda: 'Tomatoes, red, ripe, canned, packed in tomato juice',
    category: V,
    units: { CAN: 400 },
  },
  {
    pl: 'Koncentrat pomidorowy',
    en: 'Tomato paste',
    usda: "Tomato products, canned, paste, without salt added (Includes foods for USDA's Food Distribution Program)",
    category: 'SAUCES',
    units: { TEASPOON: 5, TABLESPOON: 16 },
  },
  {
    pl: 'Passata pomidorowa',
    en: 'Tomato passata',
    usda: 'Tomato products, canned, puree, without salt added',
    category: 'SAUCES',
    density: 1.04,
    units: { GLASS: 260 },
  },

  // --- Grzyby --------------------------------------------------------------------
  {
    pl: 'Pieczarki',
    en: 'White mushrooms',
    usda: 'Mushrooms, white, raw',
    category: 'MUSHROOMS',
    units: { PIECE: 20, HANDFUL: 60 },
  },
  {
    pl: 'Pieczarki portobello',
    en: 'Portobello mushrooms',
    usda: 'Mushrooms, portabella, raw',
    category: 'MUSHROOMS',
    units: { PIECE: 85 },
  },
  {
    pl: 'Boczniaki',
    en: 'Oyster mushrooms',
    usda: 'Mushrooms, oyster, raw',
    category: 'MUSHROOMS',
    units: { HANDFUL: 50 },
  },
  {
    pl: 'Grzyby shiitake',
    en: 'Shiitake mushrooms',
    usda: 'Mushrooms, shiitake, raw',
    category: 'MUSHROOMS',
    units: { PIECE: 20 },
  },
  {
    pl: 'Grzyby shiitake suszone',
    en: 'Dried shiitake',
    usda: 'Mushrooms, shiitake, dried',
    category: 'MUSHROOMS',
    units: { PIECE: 4 },
  },
  {
    pl: 'Kurki',
    en: 'Chanterelles',
    usda: 'Mushrooms, Chanterelle, raw',
    category: 'MUSHROOMS',
    units: { HANDFUL: 50 },
  },
  {
    pl: 'Smardze',
    en: 'Morels',
    usda: 'Mushrooms, morel, raw',
    category: 'MUSHROOMS',
    units: { HANDFUL: 40 },
  },

  // --- Owoce ---------------------------------------------------------------------
  {
    pl: 'Jabłko',
    en: 'Apple',
    usda: "Apples, raw, with skin (Includes foods for USDA's Food Distribution Program)",
    category: F,
    units: { PIECE: 180 },
  },
  { pl: 'Gruszka', en: 'Pear', usda: 'Pears, raw', category: F, units: { PIECE: 180 } },
  { pl: 'Banan', en: 'Banana', usda: 'Bananas, raw', category: F, units: { PIECE: 120 } },
  {
    pl: 'Pomarańcza',
    en: 'Orange',
    usda: 'Oranges, raw, all commercial varieties',
    category: F,
    units: { PIECE: 150 },
  },
  {
    pl: 'Mandarynka',
    en: 'Mandarin',
    usda: 'Tangerines, (mandarin oranges), raw',
    category: F,
    units: { PIECE: 75 },
  },
  {
    pl: 'Grejpfrut',
    en: 'Grapefruit',
    usda: 'Grapefruit, raw, pink and red and white, all areas',
    category: F,
    units: { PIECE: 250 },
  },
  {
    pl: 'Cytryna',
    en: 'Lemon',
    usda: 'Lemons, raw, without peel',
    category: F,
    units: { PIECE: 80, SLICE: 8 },
  },
  { pl: 'Limonka', en: 'Lime', usda: 'Limes, raw', category: F, units: { PIECE: 65 } },
  {
    pl: 'Sok z cytryny',
    en: 'Lemon juice',
    usda: 'Lemon juice, raw',
    category: F,
    density: 1.03,
    units: { TEASPOON: 5, TABLESPOON: 15 },
  },
  {
    pl: 'Sok z limonki',
    en: 'Lime juice',
    usda: 'Lime juice, raw',
    category: F,
    density: 1.03,
    units: { TEASPOON: 5, TABLESPOON: 15 },
  },
  {
    pl: 'Truskawki',
    en: 'Strawberries',
    usda: 'Strawberries, raw',
    category: F,
    units: { PIECE: 12, GLASS: 150, HANDFUL: 60 },
  },
  {
    pl: 'Maliny',
    en: 'Raspberries',
    usda: 'Raspberries, raw',
    category: F,
    units: { GLASS: 125, HANDFUL: 50 },
  },
  {
    pl: 'Borówki amerykańskie',
    en: 'Blueberries',
    usda: 'Blueberries, raw',
    category: F,
    units: { GLASS: 150, HANDFUL: 50 },
  },
  {
    pl: 'Jeżyny',
    en: 'Blackberries',
    usda: 'Blackberries, raw',
    category: F,
    units: { GLASS: 145, HANDFUL: 50 },
  },
  {
    pl: 'Czarna porzeczka',
    en: 'Blackcurrants',
    usda: 'Currants, european black, raw',
    category: F,
    units: { GLASS: 115, HANDFUL: 40 },
  },
  {
    pl: 'Czerwona porzeczka',
    en: 'Redcurrants',
    usda: 'Currants, red and white, raw',
    category: F,
    units: { GLASS: 115, HANDFUL: 40 },
  },
  { pl: 'Agrest', en: 'Gooseberries', usda: 'Gooseberries, raw', category: F, units: { GLASS: 150 } },
  { pl: 'Żurawina', en: 'Cranberries', usda: 'Cranberries, raw', category: F, units: { GLASS: 100 } },
  {
    pl: 'Czereśnie',
    en: 'Sweet cherries',
    usda: 'Cherries, sweet, raw',
    category: F,
    units: { PIECE: 8, GLASS: 150 },
  },
  {
    pl: 'Wiśnie',
    en: 'Sour cherries',
    usda: 'Cherries, sour, red, raw',
    category: F,
    units: { PIECE: 5, GLASS: 150 },
  },
  { pl: 'Śliwki', en: 'Plums', usda: 'Plums, raw', category: F, units: { PIECE: 65 } },
  { pl: 'Brzoskwinia', en: 'Peach', usda: 'Peaches, yellow, raw', category: F, units: { PIECE: 150 } },
  { pl: 'Nektarynka', en: 'Nectarine', usda: 'Nectarines, raw', category: F, units: { PIECE: 140 } },
  { pl: 'Morela', en: 'Apricot', usda: 'Apricots, raw', category: F, units: { PIECE: 35 } },
  {
    pl: 'Winogrona',
    en: 'Grapes',
    usda: 'Grapes, red or green (European type, such as Thompson seedless), raw',
    category: F,
    units: { PIECE: 5, GLASS: 150 },
  },
  { pl: 'Kiwi', en: 'Kiwi', usda: 'Kiwifruit, green, raw', category: F, units: { PIECE: 75 } },
  {
    pl: 'Ananas',
    en: 'Pineapple',
    usda: 'Pineapple, raw, all varieties',
    category: F,
    units: { PIECE: 900, SLICE: 80 },
  },
  { pl: 'Mango', en: 'Mango', usda: 'Mangos, raw', category: F, units: { PIECE: 200 } },
  { pl: 'Arbuz', en: 'Watermelon', usda: 'Watermelon, raw', category: F, units: { SLICE: 280 } },
  {
    pl: 'Melon kantalupa',
    en: 'Cantaloupe',
    usda: 'Melons, cantaloupe, raw',
    category: F,
    units: { PIECE: 800, SLICE: 100 },
  },
  { pl: 'Granat', en: 'Pomegranate', usda: 'Pomegranates, raw', category: F, units: { PIECE: 280 } },
  { pl: 'Figa', en: 'Fig', usda: 'Figs, raw', category: F, units: { PIECE: 50 } },
  { pl: 'Pigwa', en: 'Quince', usda: 'Quinces, raw', category: F, units: { PIECE: 90 } },
  { pl: 'Rabarbar', en: 'Rhubarb', usda: 'Rhubarb, raw', category: F, units: { PIECE: 50 } },
  {
    pl: 'Rodzynki',
    en: 'Raisins',
    usda: "Raisins, dark, seedless (Includes foods for USDA's Food Distribution Program)",
    category: F,
    allergens: ['SULPHITES'],
    units: { TABLESPOON: 10, HANDFUL: 30 },
  },
  {
    pl: 'Śliwki suszone',
    en: 'Prunes',
    usda: 'Plums, dried (prunes), uncooked',
    category: F,
    units: { PIECE: 10 },
  },
  {
    pl: 'Morele suszone',
    en: 'Dried apricots',
    usda: 'Apricots, dried, sulfured, uncooked',
    category: F,
    allergens: ['SULPHITES'],
    units: { PIECE: 7 },
  },
  { pl: 'Figi suszone', en: 'Dried figs', usda: 'Figs, dried, uncooked', category: F, units: { PIECE: 20 } },
  { pl: 'Daktyle suszone', en: 'Dates', usda: 'Dates, deglet noor', category: F, units: { PIECE: 7 } },
  { pl: 'Daktyle medjool', en: 'Medjool dates', usda: 'Dates, medjool', category: F, units: { PIECE: 24 } },
  {
    pl: 'Żurawina suszona',
    en: 'Dried cranberries',
    usda: "Cranberries, dried, sweetened (Includes foods for USDA's Food Distribution Program)",
    category: F,
    units: { TABLESPOON: 10, HANDFUL: 30 },
  },
  {
    pl: 'Wiórki kokosowe',
    en: 'Desiccated coconut',
    usda: 'Nuts, coconut meat, dried (desiccated), not sweetened',
    category: 'NUTS_SEEDS',
    units: { TABLESPOON: 6, GLASS: 80 },
  },

  // --- Rośliny strączkowe -------------------------------------------------------------
  {
    pl: 'Fasola czerwona (sucha)',
    en: 'Red kidney beans (dry)',
    usda: 'Beans, kidney, all types, mature seeds, raw',
    category: 'LEGUMES',
    units: { GLASS: 200 },
  },
  {
    pl: 'Fasola czerwona z puszki',
    en: 'Canned kidney beans',
    usda: 'Beans, kidney, all types, mature seeds, canned',
    category: 'LEGUMES',
    units: { CAN: 240 },
  },
  {
    pl: 'Fasola biała (sucha)',
    en: 'White beans (dry)',
    usda: 'Beans, white, mature seeds, raw',
    category: 'LEGUMES',
    units: { GLASS: 200 },
  },
  {
    pl: 'Fasola biała z puszki',
    en: 'Canned white beans',
    usda: 'Beans, white, mature seeds, canned',
    category: 'LEGUMES',
    units: { CAN: 240 },
  },
  {
    pl: 'Fasola czarna (sucha)',
    en: 'Black beans (dry)',
    usda: 'Beans, black, mature seeds, raw',
    category: 'LEGUMES',
    units: { GLASS: 200 },
  },
  {
    pl: 'Ciecierzyca (sucha)',
    en: 'Chickpeas (dry)',
    usda: 'Chickpeas (garbanzo beans, bengal gram), mature seeds, raw',
    category: 'LEGUMES',
    units: { GLASS: 200 },
  },
  {
    pl: 'Ciecierzyca z puszki',
    en: 'Canned chickpeas',
    usda: 'Chickpeas (garbanzo beans, bengal gram), mature seeds, canned, drained solids',
    category: 'LEGUMES',
    units: { CAN: 240 },
  },
  {
    pl: 'Soczewica zielona',
    en: 'Green lentils',
    usda: 'Lentils, raw',
    category: 'LEGUMES',
    units: { GLASS: 190 },
  },
  {
    pl: 'Soczewica czerwona',
    en: 'Red lentils',
    usda: 'Lentils, pink or red, raw',
    category: 'LEGUMES',
    units: { GLASS: 190 },
  },
  {
    pl: 'Soja (nasiona)',
    en: 'Soybeans',
    usda: 'Soybeans, mature seeds, raw',
    category: 'LEGUMES',
    allergens: ['SOY'],
    units: { GLASS: 190 },
  },
  {
    pl: 'Tofu naturalne',
    en: 'Firm tofu',
    usda: 'Tofu, raw, firm, prepared with calcium sulfate',
    category: 'LEGUMES',
    allergens: ['SOY'],
    units: { PACKAGE: 180 },
  },
  {
    pl: 'Hummus',
    en: 'Hummus',
    usda: 'Hummus, commercial',
    category: 'SAUCES',
    allergens: ['SESAME'],
    units: { TABLESPOON: 15 },
  },

  // --- Zboża, kasze, makarony --------------------------------------------------------
  {
    pl: 'Ryż biały',
    en: 'White rice',
    usda: 'Rice, white, long-grain, regular, raw, unenriched',
    category: 'GRAINS',
    units: { GLASS: 195, TABLESPOON: 12 },
  },
  {
    pl: 'Ryż do sushi / okrągłoziarnisty',
    en: 'Short-grain rice',
    usda: 'Rice, white, short-grain, raw, unenriched',
    category: 'GRAINS',
    units: { GLASS: 210 },
  },
  {
    pl: 'Ryż brązowy',
    en: 'Brown rice',
    usda: "Rice, brown, long-grain, raw (Includes foods for USDA's Food Distribution Program)",
    category: 'GRAINS',
    units: { GLASS: 195 },
  },
  {
    pl: 'Kasza gryczana palona',
    en: 'Roasted buckwheat',
    usda: 'Buckwheat groats, roasted, dry',
    category: 'GRAINS',
    units: { GLASS: 175 },
  },
  { pl: 'Kasza jaglana', en: 'Millet', usda: 'Millet, raw', category: 'GRAINS', units: { GLASS: 210 } },
  {
    pl: 'Kasza jęczmienna (pęczak)',
    en: 'Pearl barley',
    usda: 'Barley, pearled, raw',
    category: 'GRAINS',
    allergens: ['GLUTEN'],
    units: { GLASS: 210 },
  },
  {
    pl: 'Kasza bulgur',
    en: 'Bulgur',
    usda: 'Bulgur, dry',
    category: 'GRAINS',
    allergens: ['GLUTEN'],
    units: { GLASS: 150 },
  },
  {
    pl: 'Kasza kuskus',
    en: 'Couscous',
    usda: 'Couscous, dry',
    category: 'GRAINS',
    allergens: ['GLUTEN'],
    units: { GLASS: 180 },
  },
  {
    pl: 'Kasza manna',
    en: 'Semolina',
    usda: 'Semolina, unenriched',
    category: 'GRAINS',
    allergens: ['GLUTEN'],
    units: { GLASS: 175, TABLESPOON: 12 },
  },
  {
    pl: 'Komosa ryżowa (quinoa)',
    en: 'Quinoa',
    usda: 'Quinoa, uncooked',
    category: 'GRAINS',
    units: { GLASS: 180 },
  },
  {
    pl: 'Płatki owsiane',
    en: 'Rolled oats',
    usda: 'Cereals, oats, regular and quick, not fortified, dry',
    category: 'GRAINS',
    allergens: ['GLUTEN'],
    units: { GLASS: 85, TABLESPOON: 6 },
  },
  {
    pl: 'Makaron pszenny',
    en: 'Pasta',
    usda: 'Pasta, dry, unenriched',
    category: 'GRAINS',
    allergens: ['GLUTEN'],
    units: { GLASS: 100, PACKAGE: 500 },
  },
  {
    pl: 'Makaron pełnoziarnisty',
    en: 'Whole-wheat pasta',
    usda: "Pasta, whole-wheat, dry (Includes foods for USDA's Food Distribution Program)",
    category: 'GRAINS',
    allergens: ['GLUTEN'],
    units: { PACKAGE: 500 },
  },
  {
    pl: 'Makaron jajeczny',
    en: 'Egg noodles',
    usda: 'Noodles, egg, dry, unenriched',
    category: 'GRAINS',
    allergens: ['GLUTEN', 'EGGS'],
    units: { PACKAGE: 250 },
  },
  {
    pl: 'Makaron ryżowy',
    en: 'Rice noodles',
    usda: 'Rice noodles, dry',
    category: 'GRAINS',
    units: { PACKAGE: 200 },
  },
  {
    pl: 'Mąka pszenna',
    en: 'Wheat flour',
    usda: 'Wheat flour, white, all-purpose, enriched, bleached',
    category: 'BAKING',
    allergens: ['GLUTEN'],
    units: { GLASS: 150, TABLESPOON: 8, TEASPOON: 3 },
  },
  {
    pl: 'Mąka pszenna pełnoziarnista',
    en: 'Whole-wheat flour',
    usda: "Wheat flour, whole-grain (Includes foods for USDA's Food Distribution Program)",
    category: 'BAKING',
    allergens: ['GLUTEN'],
    units: { GLASS: 140, TABLESPOON: 8 },
  },
  {
    pl: 'Mąka żytnia',
    en: 'Rye flour',
    usda: 'Rye flour, medium',
    category: 'BAKING',
    allergens: ['GLUTEN'],
    units: { GLASS: 135, TABLESPOON: 8 },
  },
  {
    pl: 'Mąka kukurydziana',
    en: 'Cornmeal',
    usda: 'Cornmeal, whole-grain, yellow',
    category: 'BAKING',
    units: { GLASS: 150, TABLESPOON: 9 },
  },
  {
    pl: 'Skrobia kukurydziana',
    en: 'Cornstarch',
    usda: 'Cornstarch',
    category: 'BAKING',
    units: { TABLESPOON: 8, TEASPOON: 3 },
  },
  {
    pl: 'Mąka ziemniaczana',
    en: 'Potato starch',
    usda: 'Potato flour',
    category: 'BAKING',
    units: { TABLESPOON: 10, TEASPOON: 3 },
  },
  {
    pl: 'Bułka tarta',
    en: 'Breadcrumbs',
    usda: 'Bread, crumbs, dry, grated, plain',
    category: 'BAKERY',
    allergens: ['GLUTEN'],
    units: { TABLESPOON: 7, GLASS: 115 },
  },

  // --- Pieczywo ------------------------------------------------------------------
  {
    pl: 'Chleb pszenny',
    en: 'White bread',
    usda: 'Bread, white wheat',
    category: 'BAKERY',
    allergens: ['GLUTEN'],
    units: { SLICE: 30 },
  },
  {
    pl: 'Chleb żytni',
    en: 'Rye bread',
    usda: 'Bread, rye',
    category: 'BAKERY',
    allergens: ['GLUTEN'],
    units: { SLICE: 35 },
  },
  {
    pl: 'Chleb razowy (pumpernikiel)',
    en: 'Pumpernickel',
    usda: 'Bread, pumpernickel',
    category: 'BAKERY',
    allergens: ['GLUTEN'],
    units: { SLICE: 35 },
  },
  {
    pl: 'Chleb wieloziarnisty',
    en: 'Multigrain bread',
    usda: 'Bread, multi-grain (includes whole-grain)',
    category: 'BAKERY',
    allergens: ['GLUTEN'],
    units: { SLICE: 35 },
  },
  {
    pl: 'Chleb na zakwasie / bagietka',
    en: 'Sourdough / baguette',
    usda: 'Bread, french or vienna (includes sourdough)',
    category: 'BAKERY',
    allergens: ['GLUTEN'],
    units: { SLICE: 30, PIECE: 250 },
  },
  {
    pl: 'Bułka pszenna',
    en: 'White roll',
    usda: 'Rolls, french',
    category: 'BAKERY',
    allergens: ['GLUTEN'],
    units: { PIECE: 50 },
  },
  {
    pl: 'Bułka do hamburgera',
    en: 'Burger bun',
    usda: 'Rolls, hamburger or hotdog, plain',
    category: 'BAKERY',
    allergens: ['GLUTEN'],
    units: { PIECE: 45 },
  },
  {
    pl: 'Tortilla pszenna',
    en: 'Flour tortilla',
    usda: 'Tortillas, ready-to-bake or -fry, flour, shelf stable',
    category: 'BAKERY',
    allergens: ['GLUTEN'],
    units: { PIECE: 60 },
  },
  {
    pl: 'Tortilla kukurydziana',
    en: 'Corn tortilla',
    usda: 'Tortillas, ready-to-bake or -fry, corn',
    category: 'BAKERY',
    units: { PIECE: 26 },
  },
  {
    pl: 'Maca',
    en: 'Matzo',
    usda: 'Crackers, matzo, plain',
    category: 'BAKERY',
    allergens: ['GLUTEN'],
    units: { PIECE: 28 },
  },

  // --- Nabiał --------------------------------------------------------------------
  {
    pl: 'Mleko 3,2%',
    en: 'Whole milk',
    usda: 'Milk, whole, 3.25% milkfat, without added vitamin A and vitamin D',
    category: 'DAIRY',
    allergens: ['MILK'],
    density: 1.03,
  },
  {
    pl: 'Mleko 2%',
    en: 'Semi-skimmed milk (2%)',
    usda: 'Milk, reduced fat, fluid, 2% milkfat, without added vitamin A and vitamin D',
    category: 'DAIRY',
    allergens: ['MILK'],
    density: 1.03,
  },
  {
    pl: 'Mleko 1%',
    en: 'Low-fat milk (1%)',
    usda: 'Milk, lowfat, fluid, 1% milkfat, with added vitamin A and vitamin D',
    category: 'DAIRY',
    allergens: ['MILK'],
    density: 1.03,
  },
  {
    pl: 'Mleko odtłuszczone',
    en: 'Skimmed milk',
    usda: 'Milk, nonfat, fluid, without added vitamin A and vitamin D (fat free or skim)',
    category: 'DAIRY',
    allergens: ['MILK'],
    density: 1.03,
  },
  {
    pl: 'Mleko w proszku',
    en: 'Whole milk powder',
    usda: 'Milk, dry, whole, without added vitamin D',
    category: 'DAIRY',
    allergens: ['MILK'],
    units: { TABLESPOON: 8 },
  },
  {
    pl: 'Mleko skondensowane słodzone',
    en: 'Sweetened condensed milk',
    usda: 'Milk, canned, condensed, sweetened',
    category: 'DAIRY',
    allergens: ['MILK'],
    density: 1.3,
    units: { CAN: 400 },
  },
  {
    pl: 'Maślanka',
    en: 'Buttermilk',
    usda: 'Milk, buttermilk, fluid, cultured, lowfat',
    category: 'DAIRY',
    allergens: ['MILK'],
    density: 1.03,
  },
  {
    pl: 'Kefir',
    en: 'Kefir',
    usda: 'Kefir, lowfat, plain, LIFEWAY',
    category: 'DAIRY',
    allergens: ['MILK'],
    density: 1.03,
  },
  {
    pl: 'Jogurt naturalny',
    en: 'Plain yogurt',
    usda: 'Yogurt, plain, whole milk',
    category: 'DAIRY',
    allergens: ['MILK'],
    density: 1.04,
    units: { TABLESPOON: 15, PACKAGE: 180 },
  },
  {
    pl: 'Jogurt naturalny chudy',
    en: 'Low-fat plain yogurt',
    usda: 'Yogurt, plain, low fat',
    category: 'DAIRY',
    allergens: ['MILK'],
    density: 1.04,
    units: { TABLESPOON: 15, PACKAGE: 180 },
  },
  {
    pl: 'Jogurt grecki',
    en: 'Greek yogurt',
    usda: 'Yogurt, Greek, plain, whole milk',
    category: 'DAIRY',
    allergens: ['MILK'],
    units: { TABLESPOON: 20, PACKAGE: 400 },
  },
  {
    pl: 'Skyr / jogurt wysokobiałkowy',
    en: 'Skyr / high-protein yogurt',
    usda: "Yogurt, Greek, plain, nonfat (Includes foods for USDA's Food Distribution Program)",
    category: 'DAIRY',
    allergens: ['MILK'],
    units: { TABLESPOON: 20, PACKAGE: 150 },
  },
  {
    pl: 'Śmietana 18%',
    en: 'Sour cream (18%)',
    usda: 'Cream, sour, cultured',
    category: 'DAIRY',
    allergens: ['MILK'],
    density: 1.0,
    units: { TABLESPOON: 15 },
  },
  {
    pl: 'Śmietanka 30%',
    en: 'Whipping cream (30%)',
    usda: 'Cream, fluid, light whipping',
    category: 'DAIRY',
    allergens: ['MILK'],
    density: 0.99,
    units: { TABLESPOON: 15 },
  },
  {
    pl: 'Śmietanka 36%',
    en: 'Heavy cream (36%)',
    usda: 'Cream, fluid, heavy whipping',
    category: 'DAIRY',
    allergens: ['MILK'],
    density: 0.99,
    units: { TABLESPOON: 15 },
  },
  {
    pl: 'Śmietanka 12% (do kawy)',
    en: 'Half and half (12%)',
    usda: 'Cream, fluid, half and half',
    category: 'DAIRY',
    allergens: ['MILK'],
    density: 1.01,
    units: { TABLESPOON: 15 },
  },
  {
    pl: 'Masło',
    en: 'Butter',
    usda: 'Butter, without salt',
    category: 'FATS',
    allergens: ['MILK'],
    units: { TABLESPOON: 14, TEASPOON: 5, PACKAGE: 200 },
  },
  {
    pl: 'Masło klarowane',
    en: 'Ghee',
    usda: 'Butter oil, anhydrous',
    category: 'FATS',
    allergens: ['MILK'],
    units: { TABLESPOON: 13, TEASPOON: 4 },
  },
  {
    pl: 'Serek wiejski',
    en: 'Cottage cheese',
    usda: 'Cheese, cottage, creamed, large or small curd',
    category: 'DAIRY',
    allergens: ['MILK'],
    units: { PACKAGE: 200, TABLESPOON: 20 },
  },
  {
    pl: 'Serek wiejski lekki',
    en: 'Low-fat cottage cheese',
    usda: 'Cheese, cottage, lowfat, 2% milkfat',
    category: 'DAIRY',
    allergens: ['MILK'],
    units: { PACKAGE: 200, TABLESPOON: 20 },
  },
  {
    pl: 'Ricotta',
    en: 'Ricotta',
    usda: 'Cheese, ricotta, whole milk',
    category: 'DAIRY',
    allergens: ['MILK'],
    units: { TABLESPOON: 20, PACKAGE: 250 },
  },
  {
    pl: 'Serek śmietankowy',
    en: 'Cream cheese',
    usda: 'Cheese, cream',
    category: 'DAIRY',
    allergens: ['MILK'],
    units: { TABLESPOON: 15, PACKAGE: 200 },
  },
  {
    pl: 'Mozzarella',
    en: 'Mozzarella',
    usda: 'Cheese, mozzarella, whole milk',
    category: 'DAIRY',
    allergens: ['MILK'],
    units: { PACKAGE: 125, SLICE: 20 },
  },
  {
    pl: 'Mozzarella light',
    en: 'Part-skim mozzarella',
    usda: 'Cheese, mozzarella, part skim milk',
    category: 'DAIRY',
    allergens: ['MILK'],
    units: { PACKAGE: 125 },
  },
  {
    pl: 'Parmezan',
    en: 'Parmesan',
    usda: 'Cheese, parmesan, hard',
    category: 'DAIRY',
    allergens: ['MILK'],
    units: { TABLESPOON: 5 },
  },
  {
    pl: 'Parmezan tarty',
    en: 'Grated parmesan',
    usda: 'Cheese, parmesan, grated',
    category: 'DAIRY',
    allergens: ['MILK'],
    units: { TABLESPOON: 5, TEASPOON: 2 },
  },
  {
    pl: 'Ser gouda',
    en: 'Gouda',
    usda: 'Cheese, gouda',
    category: 'DAIRY',
    allergens: ['MILK'],
    units: { SLICE: 20 },
  },
  {
    pl: 'Ser edamski',
    en: 'Edam',
    usda: 'Cheese, edam',
    category: 'DAIRY',
    allergens: ['MILK'],
    units: { SLICE: 20 },
  },
  {
    pl: 'Ser cheddar',
    en: 'Cheddar',
    usda: "Cheese, cheddar (Includes foods for USDA's Food Distribution Program)",
    category: 'DAIRY',
    allergens: ['MILK'],
    units: { SLICE: 20 },
  },
  {
    pl: 'Ser ementaler',
    en: 'Emmental / Swiss',
    usda: 'Cheese, swiss',
    category: 'DAIRY',
    allergens: ['MILK'],
    units: { SLICE: 20 },
  },
  {
    pl: 'Ser provolone',
    en: 'Provolone',
    usda: 'Cheese, provolone',
    category: 'DAIRY',
    allergens: ['MILK'],
    units: { SLICE: 20 },
  },
  {
    pl: 'Ser feta',
    en: 'Feta',
    usda: 'Cheese, feta',
    category: 'DAIRY',
    allergens: ['MILK'],
    units: { PACKAGE: 200, TABLESPOON: 15 },
  },
  {
    pl: 'Ser pleśniowy (niebieski)',
    en: 'Blue cheese',
    usda: 'Cheese, blue',
    category: 'DAIRY',
    allergens: ['MILK'],
    units: { TABLESPOON: 15 },
  },
  {
    pl: 'Ser brie',
    en: 'Brie',
    usda: 'Cheese, brie',
    category: 'DAIRY',
    allergens: ['MILK'],
    units: { SLICE: 25 },
  },
  {
    pl: 'Ser camembert',
    en: 'Camembert',
    usda: 'Cheese, camembert',
    category: 'DAIRY',
    allergens: ['MILK'],
    units: { PACKAGE: 120, SLICE: 25 },
  },
  {
    pl: 'Ser kozi miękki',
    en: 'Soft goat cheese',
    usda: 'Cheese, goat, soft type',
    category: 'DAIRY',
    allergens: ['MILK'],
    units: { TABLESPOON: 15 },
  },

  // --- Jaja ----------------------------------------------------------------------
  {
    pl: 'Jajko',
    en: 'Egg',
    usda: 'Egg, whole, raw, fresh',
    category: 'EGGS',
    allergens: ['EGGS'],
    units: { PIECE: 50 },
  },
  {
    pl: 'Białko jaja',
    en: 'Egg white',
    usda: 'Egg, white, raw, fresh',
    category: 'EGGS',
    allergens: ['EGGS'],
    units: { PIECE: 33 },
  },
  {
    pl: 'Żółtko jaja',
    en: 'Egg yolk',
    usda: 'Egg, yolk, raw, fresh',
    category: 'EGGS',
    allergens: ['EGGS'],
    units: { PIECE: 17 },
  },

  // --- Mięso -----------------------------------------------------------------------
  {
    pl: 'Wołowina mielona 20% tłuszczu',
    en: 'Ground beef (20% fat)',
    usda: 'Beef, ground, 80% lean meat / 20% fat, raw',
    category: 'MEAT',
  },
  {
    pl: 'Wołowina mielona 15% tłuszczu',
    en: 'Ground beef (15% fat)',
    usda: "Beef, ground, 85% lean meat / 15% fat, raw (Includes foods for USDA's Food Distribution Program)",
    category: 'MEAT',
  },
  {
    pl: 'Wołowina mielona chuda',
    en: 'Lean ground beef (10% fat)',
    usda: 'Beef, ground, 90% lean meat / 10% fat, raw',
    category: 'MEAT',
  },
  {
    pl: 'Polędwica wołowa',
    en: 'Beef tenderloin',
    usda: 'Beef, tenderloin, steak, separable lean only, trimmed to 1/8" fat, all grades, raw',
    category: 'MEAT',
    units: { SLICE: 150 },
  },
  {
    pl: 'Wołowina gulaszowa',
    en: 'Beef stew meat',
    usda: 'Beef, chuck for stew, separable lean and fat, all grades, raw',
    category: 'MEAT',
  },
  {
    pl: 'Wołowina - zrazowa / pieczeń',
    en: 'Beef eye of round',
    usda: 'Beef, round, eye of round, roast, separable lean only, trimmed to 1/8" fat, all grades, raw',
    category: 'MEAT',
    units: { SLICE: 120 },
  },
  {
    pl: 'Mostek wołowy',
    en: 'Beef brisket',
    usda: 'Beef, brisket, whole, separable lean and fat, trimmed to 1/8" fat, all grades, raw',
    category: 'MEAT',
  },
  {
    pl: 'Wątróbka wołowa',
    en: 'Beef liver',
    usda: 'Beef, variety meats and by-products, liver, raw',
    category: 'MEAT',
  },
  {
    pl: 'Cielęcina (udziec)',
    en: 'Veal leg',
    usda: 'Veal, leg (top round), separable lean only, raw',
    category: 'MEAT',
    units: { SLICE: 120 },
  },
  { pl: 'Cielęcina mielona', en: 'Ground veal', usda: 'Veal, ground, raw', category: 'MEAT' },
  { pl: 'Jagnięcina mielona', en: 'Ground lamb', usda: 'Lamb, ground, raw', category: 'MEAT' },
  {
    pl: 'Polędwiczka wieprzowa',
    en: 'Pork tenderloin',
    usda: 'Pork, fresh, loin, tenderloin, separable lean only, raw',
    category: 'MEAT',
    units: { PIECE: 450 },
  },
  {
    pl: 'Schab / kotlet schabowy',
    en: 'Pork loin chop',
    usda: 'Pork, fresh, loin, center loin (chops), bone-in, separable lean and fat, raw',
    category: 'MEAT',
    units: { SLICE: 150 },
  },
  {
    pl: 'Karkówka / łopatka wieprzowa',
    en: 'Pork shoulder',
    usda: 'Pork, fresh, shoulder, whole, separable lean and fat, raw',
    category: 'MEAT',
    units: { SLICE: 150 },
  },
  {
    pl: 'Szynka wieprzowa (surowa)',
    en: 'Fresh pork leg',
    usda: 'Pork, fresh, leg (ham), whole, separable lean and fat, raw',
    category: 'MEAT',
  },
  { pl: 'Wieprzowina mielona', en: 'Ground pork', usda: 'Pork, fresh, ground, raw', category: 'MEAT' },
  {
    pl: 'Boczek surowy',
    en: 'Pork belly',
    usda: 'Pork, fresh, belly, raw',
    category: 'MEAT',
    units: { SLICE: 30 },
  },
  {
    pl: 'Żeberka wieprzowe',
    en: 'Pork spare ribs',
    usda: 'Pork, fresh, spareribs, separable lean and fat, raw',
    category: 'MEAT',
  },
  {
    pl: 'Boczek wędzony',
    en: 'Bacon',
    usda: 'Pork, cured, bacon, unprepared',
    category: 'MEAT',
    units: { SLICE: 15 },
  },
  {
    pl: 'Szynka gotowana',
    en: 'Cooked ham',
    usda: 'Ham, sliced, regular (approximately 11% fat)',
    category: 'MEAT',
    units: { SLICE: 15 },
  },
  {
    pl: 'Kiełbasa wędzona',
    en: 'Smoked sausage (kielbasa)',
    usda: 'Sausage, Polish, pork and beef, smoked',
    category: 'MEAT',
    units: { PIECE: 100, SLICE: 10 },
  },
  {
    pl: 'Kiełbasa surowa (biała)',
    en: 'Fresh pork sausage',
    usda: 'Sausage, Italian, pork, mild, raw',
    category: 'MEAT',
    units: { PIECE: 100 },
  },
  {
    pl: 'Parówka',
    en: 'Frankfurter',
    usda: 'Frankfurter, beef, unheated',
    category: 'MEAT',
    units: { PIECE: 45 },
  },

  // --- Drób ----------------------------------------------------------------------
  {
    pl: 'Pierś z kurczaka',
    en: 'Chicken breast',
    usda: 'Chicken, broiler or fryers, breast, skinless, boneless, meat only, raw',
    category: 'POULTRY',
    units: { PIECE: 200 },
  },
  {
    pl: 'Udko z kurczaka (bez skóry)',
    en: 'Chicken thigh (skinless)',
    usda: 'Chicken, broilers or fryers, dark meat, thigh, meat only, raw',
    category: 'POULTRY',
    units: { PIECE: 100 },
  },
  {
    pl: 'Udko z kurczaka (ze skórą)',
    en: 'Chicken thigh (skin-on)',
    usda: 'Chicken, broilers or fryers, thigh, meat and skin, raw',
    category: 'POULTRY',
    units: { PIECE: 130 },
  },
  {
    pl: 'Podudzie z kurczaka',
    en: 'Chicken drumstick',
    usda: 'Chicken, broilers or fryers, drumstick, meat and skin, raw',
    category: 'POULTRY',
    units: { PIECE: 90 },
  },
  {
    pl: 'Skrzydełka z kurczaka',
    en: 'Chicken wings',
    usda: 'Chicken, broilers or fryers, wing, meat and skin, raw',
    category: 'POULTRY',
    units: { PIECE: 50 },
  },
  { pl: 'Kurczak mielony', en: 'Ground chicken', usda: 'Chicken, ground, raw', category: 'POULTRY' },
  {
    pl: 'Wątróbka drobiowa',
    en: 'Chicken liver',
    usda: 'Chicken, liver, all classes, raw',
    category: 'POULTRY',
    units: { PIECE: 45 },
  },
  {
    pl: 'Pierś z indyka',
    en: 'Turkey breast',
    usda: 'Turkey, whole, breast, meat only, raw',
    category: 'POULTRY',
    units: { SLICE: 120 },
  },
  {
    pl: 'Indyk mielony',
    en: 'Ground turkey',
    usda: 'Turkey, ground, 93% lean, 7% fat, raw',
    category: 'POULTRY',
  },
  {
    pl: 'Udziec z indyka (mięso)',
    en: 'Turkey dark meat',
    usda: 'Turkey, whole, dark meat, meat only, raw',
    category: 'POULTRY',
  },
  { pl: 'Kaczka (mięso)', en: 'Duck meat', usda: 'Duck, domesticated, meat only, raw', category: 'POULTRY' },

  // --- Ryby i owoce morza -------------------------------------------------------------
  {
    pl: 'Łosoś (hodowlany)',
    en: 'Farmed salmon',
    usda: 'Fish, salmon, Atlantic, farmed, raw',
    category: 'FISH',
    allergens: ['FISH'],
    units: { PIECE: 150 },
  },
  {
    pl: 'Łosoś dziki',
    en: 'Wild salmon',
    usda: 'Fish, salmon, Atlantic, wild, raw',
    category: 'FISH',
    allergens: ['FISH'],
    units: { PIECE: 150 },
  },
  {
    pl: 'Łosoś wędzony',
    en: 'Smoked salmon',
    usda: 'Fish, salmon, chinook, smoked',
    category: 'FISH',
    allergens: ['FISH'],
    units: { SLICE: 20, PACKAGE: 100 },
  },
  {
    pl: 'Dorsz',
    en: 'Cod',
    usda: 'Fish, cod, Atlantic, raw',
    category: 'FISH',
    allergens: ['FISH'],
    units: { PIECE: 150 },
  },
  {
    pl: 'Mintaj',
    en: 'Alaska pollock',
    usda: 'Fish, pollock, Alaska, raw',
    category: 'FISH',
    allergens: ['FISH'],
    units: { PIECE: 120 },
  },
  {
    pl: 'Morszczuk / łupacz',
    en: 'Haddock',
    usda: 'Fish, haddock, raw',
    category: 'FISH',
    allergens: ['FISH'],
    units: { PIECE: 150 },
  },
  {
    pl: 'Tilapia',
    en: 'Tilapia',
    usda: 'Fish, tilapia, raw',
    category: 'FISH',
    allergens: ['FISH'],
    units: { PIECE: 120 },
  },
  {
    pl: 'Pstrąg',
    en: 'Rainbow trout',
    usda: 'Fish, trout, rainbow, farmed, raw',
    category: 'FISH',
    allergens: ['FISH'],
    units: { PIECE: 250 },
  },
  {
    pl: 'Karp',
    en: 'Carp',
    usda: 'Fish, carp, raw',
    category: 'FISH',
    allergens: ['FISH'],
    units: { PIECE: 200 },
  },
  { pl: 'Szczupak', en: 'Pike', usda: 'Fish, pike, northern, raw', category: 'FISH', allergens: ['FISH'] },
  { pl: 'Okoń', en: 'Perch', usda: 'Fish, perch, mixed species, raw', category: 'FISH', allergens: ['FISH'] },
  {
    pl: 'Makrela',
    en: 'Mackerel',
    usda: 'Fish, mackerel, Atlantic, raw',
    category: 'FISH',
    allergens: ['FISH'],
    units: { PIECE: 200 },
  },
  {
    pl: 'Śledź',
    en: 'Herring',
    usda: 'Fish, herring, Atlantic, raw',
    category: 'FISH',
    allergens: ['FISH'],
    units: { PIECE: 100 },
  },
  {
    pl: 'Śledź marynowany',
    en: 'Pickled herring',
    usda: 'Fish, herring, Atlantic, pickled',
    category: 'FISH',
    allergens: ['FISH'],
    units: { PIECE: 50 },
  },
  {
    pl: 'Tuńczyk świeży',
    en: 'Fresh tuna',
    usda: 'Fish, tuna, fresh, yellowfin, raw',
    category: 'FISH',
    allergens: ['FISH'],
    units: { PIECE: 150 },
  },
  {
    pl: 'Tuńczyk w sosie własnym',
    en: 'Canned tuna in water',
    usda: "Fish, tuna, light, canned in water, drained solids (Includes foods for USDA's Food Distribution Program)",
    category: 'FISH',
    allergens: ['FISH'],
    units: { CAN: 120 },
  },
  {
    pl: 'Tuńczyk w oleju',
    en: 'Canned tuna in oil',
    usda: 'Fish, tuna, light, canned in oil, drained solids',
    category: 'FISH',
    allergens: ['FISH'],
    units: { CAN: 120 },
  },
  {
    pl: 'Sardynki w oleju',
    en: 'Sardines in oil',
    usda: 'Fish, sardine, Atlantic, canned in oil, drained solids with bone',
    category: 'FISH',
    allergens: ['FISH'],
    units: { CAN: 90, PIECE: 12 },
  },
  {
    pl: 'Krewetki',
    en: 'Shrimp',
    usda: 'Crustaceans, shrimp, raw',
    category: 'FISH',
    allergens: ['CRUSTACEANS'],
    units: { PIECE: 12, HANDFUL: 80 },
  },
  {
    pl: 'Małże (omułki)',
    en: 'Mussels',
    usda: 'Mollusks, mussel, blue, raw',
    category: 'FISH',
    allergens: ['MOLLUSCS'],
  },
  {
    pl: 'Kalmary',
    en: 'Squid',
    usda: 'Mollusks, squid, mixed species, raw',
    category: 'FISH',
    allergens: ['MOLLUSCS'],
  },
  {
    pl: 'Małże (clams)',
    en: 'Clams',
    usda: 'Mollusks, clam, mixed species, raw',
    category: 'FISH',
    allergens: ['MOLLUSCS'],
  },

  // --- Orzechy i nasiona -----------------------------------------------------------
  {
    pl: 'Migdały',
    en: 'Almonds',
    usda: 'Nuts, almonds',
    category: 'NUTS_SEEDS',
    allergens: ['NUTS'],
    units: { PIECE: 1.2, HANDFUL: 30, TABLESPOON: 9 },
  },
  {
    pl: 'Orzechy włoskie',
    en: 'Walnuts',
    usda: 'Nuts, walnuts, english',
    category: 'NUTS_SEEDS',
    allergens: ['NUTS'],
    units: { PIECE: 5, HANDFUL: 30, TABLESPOON: 7 },
  },
  {
    pl: 'Orzechy laskowe',
    en: 'Hazelnuts',
    usda: 'Nuts, hazelnuts or filberts',
    category: 'NUTS_SEEDS',
    allergens: ['NUTS'],
    units: { PIECE: 1.5, HANDFUL: 30, TABLESPOON: 9 },
  },
  {
    pl: 'Orzechy nerkowca',
    en: 'Cashews',
    usda: 'Nuts, cashew nuts, raw',
    category: 'NUTS_SEEDS',
    allergens: ['NUTS'],
    units: { PIECE: 1.5, HANDFUL: 30 },
  },
  {
    pl: 'Pistacje',
    en: 'Pistachios',
    usda: 'Nuts, pistachio nuts, raw',
    category: 'NUTS_SEEDS',
    allergens: ['NUTS'],
    units: { HANDFUL: 30 },
  },
  {
    pl: 'Orzechy pekan',
    en: 'Pecans',
    usda: 'Nuts, pecans',
    category: 'NUTS_SEEDS',
    allergens: ['NUTS'],
    units: { HANDFUL: 30 },
  },
  {
    pl: 'Orzechy brazylijskie',
    en: 'Brazil nuts',
    usda: 'Nuts, brazilnuts, dried, unblanched',
    category: 'NUTS_SEEDS',
    allergens: ['NUTS'],
    units: { PIECE: 5 },
  },
  {
    pl: 'Orzechy makadamia',
    en: 'Macadamia nuts',
    usda: 'Nuts, macadamia nuts, raw',
    category: 'NUTS_SEEDS',
    allergens: ['NUTS'],
    units: { HANDFUL: 30 },
  },
  {
    pl: 'Orzeszki piniowe',
    en: 'Pine nuts',
    usda: 'Nuts, pine nuts, dried',
    category: 'NUTS_SEEDS',
    allergens: ['NUTS'],
    units: { TABLESPOON: 9 },
  },
  {
    pl: 'Orzeszki ziemne',
    en: 'Peanuts',
    usda: 'Peanuts, all types, raw',
    category: 'NUTS_SEEDS',
    allergens: ['PEANUTS'],
    units: { HANDFUL: 30, TABLESPOON: 9 },
  },
  {
    pl: 'Masło orzechowe',
    en: 'Peanut butter',
    usda: 'Peanut butter, smooth style, without salt',
    category: 'NUTS_SEEDS',
    allergens: ['PEANUTS'],
    units: { TABLESPOON: 16, TEASPOON: 5 },
  },
  {
    pl: 'Pestki słonecznika',
    en: 'Sunflower seeds',
    usda: 'Seeds, sunflower seed kernels, dried',
    category: 'NUTS_SEEDS',
    units: { TABLESPOON: 9, HANDFUL: 30 },
  },
  {
    pl: 'Pestki dyni',
    en: 'Pumpkin seeds',
    usda: 'Seeds, pumpkin and squash seed kernels, dried',
    category: 'NUTS_SEEDS',
    units: { TABLESPOON: 9, HANDFUL: 30 },
  },
  {
    pl: 'Sezam',
    en: 'Sesame seeds',
    usda: 'Seeds, sesame seeds, whole, dried',
    category: 'NUTS_SEEDS',
    allergens: ['SESAME'],
    units: { TABLESPOON: 9, TEASPOON: 3 },
  },
  {
    pl: 'Nasiona chia',
    en: 'Chia seeds',
    usda: 'Seeds, chia seeds, dried',
    category: 'NUTS_SEEDS',
    units: { TABLESPOON: 12, TEASPOON: 4 },
  },
  {
    pl: 'Siemię lniane',
    en: 'Flaxseed',
    usda: 'Seeds, flaxseed',
    category: 'NUTS_SEEDS',
    units: { TABLESPOON: 10, TEASPOON: 3 },
  },
  {
    pl: 'Nasiona konopi łuskane',
    en: 'Hulled hemp seeds',
    usda: 'Seeds, hemp seed, hulled',
    category: 'NUTS_SEEDS',
    units: { TABLESPOON: 10 },
  },

  // --- Tłuszcze i oleje -----------------------------------------------------------
  {
    pl: 'Oliwa z oliwek',
    en: 'Olive oil',
    usda: 'Oil, olive, salad or cooking',
    category: 'FATS',
    density: 0.92,
    units: { TABLESPOON: 14, TEASPOON: 4.5 },
  },
  {
    pl: 'Olej rzepakowy',
    en: 'Rapeseed (canola) oil',
    usda: 'Oil, canola',
    category: 'FATS',
    density: 0.92,
    units: { TABLESPOON: 14, TEASPOON: 4.5 },
  },
  {
    pl: 'Olej słonecznikowy',
    en: 'Sunflower oil',
    usda: 'Oil, sunflower, linoleic (less than 60%)',
    category: 'FATS',
    density: 0.92,
    units: { TABLESPOON: 14, TEASPOON: 4.5 },
  },
  {
    pl: 'Olej kokosowy',
    en: 'Coconut oil',
    usda: 'Oil, coconut',
    category: 'FATS',
    density: 0.92,
    units: { TABLESPOON: 14, TEASPOON: 4.5 },
  },
  {
    pl: 'Olej sezamowy',
    en: 'Sesame oil',
    usda: 'Oil, sesame, salad or cooking',
    category: 'FATS',
    allergens: ['SESAME'],
    density: 0.92,
    units: { TABLESPOON: 14, TEASPOON: 4.5 },
  },
  {
    pl: 'Olej arachidowy',
    en: 'Peanut oil',
    usda: 'Oil, peanut, salad or cooking',
    category: 'FATS',
    allergens: ['PEANUTS'],
    density: 0.92,
    units: { TABLESPOON: 14, TEASPOON: 4.5 },
  },
  { pl: 'Smalec', en: 'Lard', usda: 'Lard', category: 'FATS', units: { TABLESPOON: 13, TEASPOON: 4 } },
  {
    pl: 'Margaryna',
    en: 'Margarine',
    usda: 'Margarine, regular, 80% fat, composite, stick, with salt',
    category: 'FATS',
    units: { TABLESPOON: 14, TEASPOON: 5 },
  },

  // --- Zioła i przyprawy -----------------------------------------------------------
  {
    pl: 'Sól',
    en: 'Salt',
    usda: 'Salt, table',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 6, PINCH: 0.4 },
  },
  {
    pl: 'Pieprz czarny mielony',
    en: 'Ground black pepper',
    usda: 'Spices, pepper, black',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 2.3, PINCH: 0.2 },
  },
  {
    pl: 'Papryka słodka mielona',
    en: 'Paprika',
    usda: 'Spices, paprika',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 2.3 },
  },
  {
    pl: 'Pieprz cayenne',
    en: 'Cayenne pepper',
    usda: 'Spices, pepper, red or cayenne',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 1.8, PINCH: 0.2 },
  },
  {
    pl: 'Chili w proszku',
    en: 'Chili powder',
    usda: 'Spices, chili powder',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 2.7 },
  },
  {
    pl: 'Cynamon',
    en: 'Cinnamon',
    usda: 'Spices, cinnamon, ground',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 2.6, PINCH: 0.3 },
  },
  {
    pl: 'Kmin rzymski',
    en: 'Cumin',
    usda: 'Spices, cumin seed',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 2 },
  },
  {
    pl: 'Kminek',
    en: 'Caraway seeds',
    usda: 'Spices, caraway seed',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 2 },
  },
  {
    pl: 'Kolendra (nasiona)',
    en: 'Coriander seeds',
    usda: 'Spices, coriander seed',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 1.8 },
  },
  {
    pl: 'Kurkuma',
    en: 'Turmeric',
    usda: 'Spices, turmeric, ground',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 3 },
  },
  {
    pl: 'Imbir mielony',
    en: 'Ground ginger',
    usda: 'Spices, ginger, ground',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 1.8 },
  },
  {
    pl: 'Curry',
    en: 'Curry powder',
    usda: 'Spices, curry powder',
    category: 'HERBS_SPICES',
    allergens: ['MUSTARD'],
    units: { TEASPOON: 2 },
  },
  {
    pl: 'Gałka muszkatołowa',
    en: 'Nutmeg',
    usda: 'Spices, nutmeg, ground',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 2.2, PINCH: 0.2 },
  },
  {
    pl: 'Goździki mielone',
    en: 'Ground cloves',
    usda: 'Spices, cloves, ground',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 2.1 },
  },
  {
    pl: 'Ziele angielskie',
    en: 'Allspice',
    usda: 'Spices, allspice, ground',
    category: 'HERBS_SPICES',
    units: { PIECE: 0.1, TEASPOON: 1.9 },
  },
  {
    pl: 'Liść laurowy',
    en: 'Bay leaf',
    usda: 'Spices, bay leaf',
    category: 'HERBS_SPICES',
    units: { PIECE: 0.2 },
  },
  {
    pl: 'Kardamon',
    en: 'Cardamom',
    usda: 'Spices, cardamom',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 2 },
  },
  {
    pl: 'Koper włoski (nasiona)',
    en: 'Fennel seeds',
    usda: 'Spices, fennel seed',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 2 },
  },
  {
    pl: 'Czosnek granulowany',
    en: 'Garlic powder',
    usda: 'Spices, garlic powder',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 3 },
  },
  {
    pl: 'Cebula suszona',
    en: 'Onion powder',
    usda: 'Spices, onion powder',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 2.4 },
  },
  {
    pl: 'Oregano suszone',
    en: 'Dried oregano',
    usda: 'Spices, oregano, dried',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 1 },
  },
  {
    pl: 'Bazylia suszona',
    en: 'Dried basil',
    usda: 'Spices, basil, dried',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 0.7 },
  },
  {
    pl: 'Tymianek suszony',
    en: 'Dried thyme',
    usda: 'Spices, thyme, dried',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 1 },
  },
  {
    pl: 'Majeranek',
    en: 'Marjoram',
    usda: 'Spices, marjoram, dried',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 0.6 },
  },
  {
    pl: 'Rozmaryn suszony',
    en: 'Dried rosemary',
    usda: 'Spices, rosemary, dried',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 1.2 },
  },
  {
    pl: 'Koperek suszony',
    en: 'Dried dill',
    usda: 'Spices, dill weed, dried',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 1 },
  },
  {
    pl: 'Natka pietruszki suszona',
    en: 'Dried parsley',
    usda: 'Spices, parsley, dried',
    category: 'HERBS_SPICES',
    units: { TEASPOON: 0.5 },
  },
  {
    pl: 'Natka pietruszki',
    en: 'Fresh parsley',
    usda: 'Parsley, fresh',
    category: 'HERBS_SPICES',
    units: { TABLESPOON: 4, BUNCH: 50 },
  },
  {
    pl: 'Koperek',
    en: 'Fresh dill',
    usda: 'Dill weed, fresh',
    category: 'HERBS_SPICES',
    units: { TABLESPOON: 3, BUNCH: 40 },
  },
  {
    pl: 'Szczypiorek',
    en: 'Chives',
    usda: 'Chives, raw',
    category: 'HERBS_SPICES',
    units: { TABLESPOON: 3, BUNCH: 30 },
  },
  {
    pl: 'Bazylia świeża',
    en: 'Fresh basil',
    usda: 'Basil, fresh',
    category: 'HERBS_SPICES',
    units: { HANDFUL: 10, BUNCH: 30 },
  },
  {
    pl: 'Drożdże świeże',
    en: 'Fresh yeast',
    usda: "Leavening agents, yeast, baker's, compressed",
    category: 'BAKING',
    units: { PACKAGE: 100 },
  },
  {
    pl: 'Drożdże suszone',
    en: 'Dry yeast',
    usda: "Leavening agents, yeast, baker's, active dry",
    category: 'BAKING',
    units: { PACKAGE: 7, TEASPOON: 3 },
  },
  {
    pl: 'Proszek do pieczenia',
    en: 'Baking powder',
    usda: 'Leavening agents, baking powder, double-acting, sodium aluminum sulfate',
    category: 'BAKING',
    units: { TEASPOON: 4.6, PACKAGE: 30 },
  },
  {
    pl: 'Soda oczyszczona',
    en: 'Baking soda',
    usda: 'Leavening agents, baking soda',
    category: 'BAKING',
    units: { TEASPOON: 4.6 },
  },
  {
    pl: 'Żelatyna',
    en: 'Gelatin',
    usda: 'Gelatins, dry powder, unsweetened',
    category: 'BAKING',
    units: { TEASPOON: 3, TABLESPOON: 9, PACKAGE: 20 },
  },
  {
    pl: 'Kakao',
    en: 'Cocoa powder',
    usda: 'Cocoa, dry powder, unsweetened',
    category: 'BAKING',
    units: { TABLESPOON: 5.4, TEASPOON: 1.8 },
  },
  {
    pl: 'Ekstrakt waniliowy',
    en: 'Vanilla extract',
    usda: 'Vanilla extract',
    category: 'BAKING',
    density: 0.88,
    units: { TEASPOON: 4.2 },
  },
  {
    pl: 'Czekolada gorzka 70-85%',
    en: 'Dark chocolate 70-85%',
    usda: 'Chocolate, dark, 70-85% cacao solids',
    category: 'SWEETS',
    allergens: ['MILK', 'SOY'],
    units: { PIECE: 5, PACKAGE: 100 },
  },
  {
    pl: 'Czekolada do pieczenia (100%)',
    en: 'Unsweetened baking chocolate',
    usda: 'Baking chocolate, unsweetened, squares',
    category: 'BAKING',
    units: { PACKAGE: 100 },
  },

  // --- Sosy i dodatki ------------------------------------------------------------
  {
    pl: 'Majonez',
    en: 'Mayonnaise',
    usda: 'Salad dressing, mayonnaise, regular',
    category: 'SAUCES',
    allergens: ['EGGS', 'MUSTARD'],
    units: { TABLESPOON: 14, TEASPOON: 5 },
  },
  {
    pl: 'Musztarda',
    en: 'Mustard',
    usda: 'Mustard, prepared, yellow',
    category: 'SAUCES',
    allergens: ['MUSTARD'],
    units: { TEASPOON: 5, TABLESPOON: 15 },
  },
  {
    pl: 'Ketchup',
    en: 'Ketchup',
    usda: 'Catsup',
    category: 'SAUCES',
    units: { TABLESPOON: 17, TEASPOON: 6 },
  },
  {
    pl: 'Sos sojowy',
    en: 'Soy sauce',
    usda: 'Soy sauce made from soy and wheat (shoyu)',
    category: 'SAUCES',
    allergens: ['SOY', 'GLUTEN'],
    density: 1.13,
    units: { TABLESPOON: 16, TEASPOON: 5.5 },
  },
  {
    pl: 'Sos Worcestershire',
    en: 'Worcestershire sauce',
    usda: 'Sauce, worcestershire',
    category: 'SAUCES',
    allergens: ['FISH'],
    density: 1.13,
    units: { TEASPOON: 5.5 },
  },
  {
    pl: 'Pesto bazyliowe',
    en: 'Basil pesto',
    usda: 'Sauce, pesto, ready-to-serve, refrigerated',
    category: 'SAUCES',
    allergens: ['MILK', 'NUTS'],
    units: { TABLESPOON: 16 },
  },
  {
    pl: 'Sos pomidorowy',
    en: 'Tomato sauce',
    usda: 'Tomato products, canned, sauce',
    category: 'SAUCES',
    density: 1.03,
  },
  {
    pl: 'Ocet jabłkowy',
    en: 'Apple cider vinegar',
    usda: 'Vinegar, cider',
    category: 'SAUCES',
    density: 1.01,
    units: { TABLESPOON: 15, TEASPOON: 5 },
  },
  {
    pl: 'Ocet spirytusowy',
    en: 'White vinegar',
    usda: 'Vinegar, distilled',
    category: 'SAUCES',
    allergens: ['SULPHITES'],
    density: 1.01,
    units: { TABLESPOON: 15, TEASPOON: 5 },
  },
  {
    pl: 'Ocet balsamiczny',
    en: 'Balsamic vinegar',
    usda: 'Vinegar, balsamic',
    category: 'SAUCES',
    allergens: ['SULPHITES'],
    density: 1.06,
    units: { TABLESPOON: 16, TEASPOON: 5 },
  },
  {
    pl: 'Mleko kokosowe',
    en: 'Coconut milk',
    usda: 'Nuts, coconut milk, canned (liquid expressed from grated meat and water)',
    category: 'SAUCES',
    density: 1.0,
    units: { CAN: 400 },
  },
  {
    pl: 'Bulion drobiowy',
    en: 'Chicken stock',
    usda: 'Soup, stock, chicken, home-prepared',
    category: 'SAUCES',
    allergens: ['CELERY'],
    density: 1.0,
  },

  // --- Słodycze i słodziki ------------------------------------------------------------
  {
    pl: 'Cukier',
    en: 'Sugar',
    usda: 'Sugars, granulated',
    category: 'SWEETS',
    units: { TABLESPOON: 12.5, TEASPOON: 4.2, GLASS: 220 },
  },
  {
    pl: 'Cukier trzcinowy brązowy',
    en: 'Brown sugar',
    usda: 'Sugars, brown',
    category: 'SWEETS',
    units: { TABLESPOON: 13, TEASPOON: 4.5 },
  },
  {
    pl: 'Cukier puder',
    en: 'Powdered sugar',
    usda: 'Sugars, powdered',
    category: 'SWEETS',
    units: { TABLESPOON: 8, TEASPOON: 2.5, GLASS: 130 },
  },
  {
    pl: 'Miód',
    en: 'Honey',
    usda: 'Honey',
    category: 'SWEETS',
    density: 1.42,
    units: { TABLESPOON: 21, TEASPOON: 7 },
  },
  {
    pl: 'Syrop klonowy',
    en: 'Maple syrup',
    usda: 'Syrups, maple',
    category: 'SWEETS',
    density: 1.32,
    units: { TABLESPOON: 20, TEASPOON: 6.6 },
  },
  {
    pl: 'Melasa',
    en: 'Molasses',
    usda: 'Molasses',
    category: 'SWEETS',
    density: 1.4,
    units: { TABLESPOON: 20 },
  },
  {
    pl: 'Dżem',
    en: 'Jam',
    usda: 'Jams and preserves',
    category: 'SWEETS',
    units: { TABLESPOON: 20, TEASPOON: 7 },
  },

  // --- Napoje --------------------------------------------------------------------
  { pl: 'Woda', en: 'Water', usda: 'Beverages, water, tap, drinking', category: 'BEVERAGES', density: 1.0 },
  {
    pl: 'Kawa (napar)',
    en: 'Brewed coffee',
    usda: 'Beverages, coffee, brewed, prepared with tap water',
    category: 'BEVERAGES',
    density: 1.0,
  },
  {
    pl: 'Kawa rozpuszczalna',
    en: 'Instant coffee',
    usda: 'Beverages, coffee, instant, regular, powder',
    category: 'BEVERAGES',
    units: { TEASPOON: 1.8 },
  },
  {
    pl: 'Herbata czarna (napar)',
    en: 'Brewed black tea',
    usda: 'Beverages, tea, black, brewed, prepared with tap water',
    category: 'BEVERAGES',
    density: 1.0,
  },
  {
    pl: 'Sok pomarańczowy',
    en: 'Orange juice',
    usda: "Orange juice, raw (Includes foods for USDA's Food Distribution Program)",
    category: 'BEVERAGES',
    density: 1.04,
  },
  {
    pl: 'Sok jabłkowy',
    en: 'Apple juice',
    usda: 'Apple juice, canned or bottled, unsweetened, without added ascorbic acid',
    category: 'BEVERAGES',
    density: 1.04,
  },
  {
    pl: 'Napój migdałowy niesłodzony',
    en: 'Unsweetened almond drink',
    usda: 'Beverages, almond milk, unsweetened, shelf stable',
    category: 'BEVERAGES',
    allergens: ['NUTS'],
    density: 1.02,
  },
  {
    pl: 'Napój ryżowy',
    en: 'Rice drink',
    usda: 'Beverages, rice milk, unsweetened',
    category: 'BEVERAGES',
    density: 1.02,
  },
  {
    pl: 'Wino czerwone wytrawne',
    en: 'Dry red wine',
    usda: 'Alcoholic beverage, wine, table, red',
    category: 'BEVERAGES',
    allergens: ['SULPHITES'],
    density: 0.99,
  },
  {
    pl: 'Wino białe wytrawne',
    en: 'Dry white wine',
    usda: 'Alcoholic beverage, wine, table, white',
    category: 'BEVERAGES',
    allergens: ['SULPHITES'],
    density: 0.99,
  },
  {
    pl: 'Piwo jasne',
    en: 'Lager beer',
    usda: 'Alcoholic beverage, beer, regular, all',
    category: 'BEVERAGES',
    allergens: ['GLUTEN'],
    density: 1.01,
  },
];
